protected/controllers/DrawController.php
<?php

class DrawController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view', 'create', 'update', 'admin', 'result', 'random', 'getrandom', 'validate', 'randomize', 'result1'),
                'users' => array('*'),
            ),
            /* array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array(),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('delete'),
                'users'=>array('admin'),
            ), */
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('reset', 'cleardata', 'generate', 'generate2', 'generate3'),
                'users' => array('bpr'),
            ),
            array('deny',  // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new Draw;

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

        if (isset($_POST['Draw'])) {
            $model->attributes = $_POST['Draw'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

        if (isset($_POST['Draw'])) {
            $model->attributes = $_POST['Draw'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        if (Yii::app()->request->isPostRequest) {
// we only allow deletion via POST request
            $this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        } else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider = new CActiveDataProvider('Draw');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model = new Draw('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Draw']))
            $model->attributes = $_GET['Draw'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    public function actionResult()
    {

        $this->layout = 'column1';

        /* $criteria = new CDbCriteria;
        $criteria->compare('gift_id','1');
        //$model = Draw::model()->findAll($criteria);
        $model = new CActiveDataProvider('Draw', array(
				'criteria'=>$criteria,
			));
        
        $criteria2 = new CDbCriteria;
        $criteria2->compare('gift_id','2');
        //$model2 = Draw::model()->findAll($criteria2);
        $model2 = new CActiveDataProvider('Draw', array(
				'criteria'=>$criteria2,
			));
        
        $criteria3 = new CDbCriteria;
        $criteria3->compare('gift_id','3');
        //$model3 = Draw::model()->findAll($criteria3);
        $model3 = new CActiveDataProvider('Draw', array(
				'criteria'=>$criteria3,
			));
        
        $criteria4 = new CDbCriteria;
        $criteria4->compare('gift_id','4');
        //$model4 = Draw::model()->findAll($criteria4);
        $model4 = new CActiveDataProvider('Draw', array(
				'criteria'=>$criteria4,
			));
        
        $criteria5 = new CDbCriteria;
        $criteria5->compare('gift_id','5');
        //$model5 = Draw::model()->findAll($criteria5);
        $model5 = new CActiveDataProvider('Draw', array(
				'criteria'=>$criteria5,
			));
        
        $criteria6 = new CDbCriteria;
        $criteria6->compare('gift_id','6');
        //$model6 = Draw::model()->findAll($criteria6);
        $model6 = new CActiveDataProvider('Draw', array(
				'criteria'=>$criteria6,
			)); */


        $model = new Draw('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Draw'])) {
            $model->attributes = $_GET['Draw'];
        }

        $this->render('result', array(
            'model' => $model,
            /* 'model2'=>$model2,
            'model3'=>$model3,
            'model4'=>$model4,
            'model5'=>$model5,
            'model6'=>$model6, */
        ));
    }

    public function actionRandom($gift)
    {
        /*get Hadiah*/
        $model = Gift::model()->findByPk($gift);

        /*begin random*/
        $dataNo = Client::model()->findAll(array(
            'condition' => 'status = 50',
        ));
        $arrData = array();
        foreach ($dataNo as $val) {
            $arrData[$val->id] = $val->id;
        }
        //print_r($arrData);
        //$random = array_rand($arrData,1);
        for ($i = 1; $i <= 20; $i++) {
            $random = array_rand($arrData, 1);
        }
        /* echo $random;
        echo '**'; */
        $range = Client::model()->find(array(
            'select' => 'id, start_no, finish_no',
            'condition' => 'id = :r',
            'params' => array(':r' => $random),
        ));

        $min = $range->start_no;
        $max = $range->finish_no;

        for ($i = 1; $i <= 20; $i++) {
            $undian = rand($min, $max);
        }
        /* echo $undian; */
        /*emd random*/

        //$count = '9';

        //$arrs = '["' . implode('", "', $arrUndian) . '"]';
        $this->render('random', array(
            'model' => $model,
            //'arrs'=>$arrs,
            //'count'=>$count,
        ));
    }

    public function actionRandomize()
    {
        do {
            $comm = Yii::app()->db->createCommand("
				(SELECT CEIL(RAND() * MAX(id)) as a FROM point where status=1)
				");
            $x = $comm->queryAll();
            $idPoint = $x[0]['a'];

            $user = Yii::app()->db->createCommand()
                ->select('id, point, client_id')
                ->from('point')
                ->where('id=:id', array(':id' => $idPoint))
                ->queryRow();
        } while ($user === false);

        $point2020 = $user;
        $poin = $user['point'];
        $cid = $user['client_id'];

        $command = Yii::app()->db->createCommand("select id,cif,account_no,fullname,status from client WHERE id='$cid'");
        $model = $command->queryRow();
        if ($model != null && $model['status'] == '50') {
            $temp = array("id" => $model['id'], "undian" => $poin, "nama" => $model['fullname'], "account" => $model['account_no'], "cif" => $model['cif']);
        } else {
            $dataNo = Client::model()->findAll(array(
                'condition' => 'status = 50',
            ));
            $arrData = array();
            foreach ($dataNo as $val) {
                $arrData[$val->id] = $val->id;
            }

            $random = array_rand($arrData, 1);

            $range = Client::model()->find(array(
                'select' => 'id, start_no, finish_no',
                'condition' => 'id = :r',
                'params' => array(':r' => $random),
            ));

            $min = $range->start_no;
            $max = $range->finish_no;

            for ($i = 1; $i <= 20; $i++) {
                $undian = rand($min, $max);
            }

            $command1 = Yii::app()->db->createCommand("select id,cif,account_no,fullname from client WHERE ('$undian' BETWEEN start_no and finish_no) AND status=50");
            $model1 = $command1->queryRow();
            file_put_contents('' . $undian . '.txt', $poin . 'diganti' . $undian);
            $temp = array("id" => $model1['id'], "undian" => $undian, "nama" => $model1['fullname'], "account" => $model1['account_no'], "cif" => $model1['cif']);

        }
        $point2020['data'] = $temp;
        echo json_encode($point2020);
    }

protected/controllers/GiftController.php
<?php

class GiftController extends Controller
{
    /**
    * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
    * using two-column layout. See 'protected/views/layouts/column2.php'.
    */
    public $layout='//layouts/column2';

    /**
    * @return array action filters
    */
    public function filters()
    {
    return array(
        'accessControl', // perform access control for CRUD operations
        );
    }

    /**
    * Specifies the access control rules.
    * This method is used by the 'accessControl' filter.
    * @return array access control rules
    */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','view','create','update','admin','choose'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array(),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('delete'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    /**
    * Displays a particular model.
    * @param integer $id the ID of the model to be displayed
    */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }

    /**
    * Creates a new model.
    * If creation is successful, the browser will be redirected to the 'view' page.
    */
    public function actionCreate()
    {
    $model=new Gift;

    // Uncomment the following line if AJAX validation is needed
    // $this->performAjaxValidation($model);

    if(isset($_POST['Gift']))
    {
    $model->attributes=$_POST['Gift'];
    if($model->save())
    $this->redirect(array('view','id'=>$model->id));
    }

    $this->render('create',array(
    'model'=>$model,
    ));
    }

    /**
    * Updates a particular model.
    * If update is successful, the browser will be redirected to the 'view' page.
    * @param integer $id the ID of the model to be updated
    */
    public function actionUpdate($id)
    {
    $model=$this->loadModel($id);

    // Uncomment the following line if AJAX validation is needed
    // $this->performAjaxValidation($model);

    if(isset($_POST['Gift']))
    {
    $model->attributes=$_POST['Gift'];
    if($model->save())
    $this->redirect(array('view','id'=>$model->id));
    }

    $this->render('update',array(
    'model'=>$model,
    ));
    }

    /**
    * Deletes a particular model.
    * If deletion is successful, the browser will be redirected to the 'admin' page.
    * @param integer $id the ID of the model to be deleted
    */
    public function actionDelete($id)
    {
    if(Yii::app()->request->isPostRequest)
    {
    // we only allow deletion via POST request
    $this->loadModel($id)->delete();

    // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
    if(!isset($_GET['ajax']))
    $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }
    else
    throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
    }

    /**
    * Lists all models.
    */
    public function actionIndex()
    {
    $dataProvider=new CActiveDataProvider('Gift');
    $this->render('index',array(
    'dataProvider'=>$dataProvider,
    ));
    }

    /**
    * Manages all models.
    */
    public function actionAdmin()
    {
    $model=new Gift('search');
    $model->unsetAttributes();  // clear any default values
    if(isset($_GET['Gift']))
    $model->attributes=$_GET['Gift'];

    $this->render('admin',array(
    'model'=>$model,
    ));
    }

    public function actionChoose(){
        $dataProvider=new CActiveDataProvider('Gift');
        $this->render('choose',array(
            'dataProvider'=>$dataProvider,
        ));
    }

    /**
    * Returns the data model based on the primary key given in the GET variable.
    * If the data model is not found, an HTTP exception will be raised.
    * @param integer the ID of the model to be loaded
    */
    public function loadModel($id)
    {
    $model=Gift::model()->findByPk($id);
    if($model===null)
    throw new CHttpException(404,'The requested page does not exist.');
    return $model;
    }

    /**
    * Performs the AJAX validation.
    * @param CModel the model to be validated
    */
    protected function performAjaxValidation($model)
    {
    if(isset($_POST['ajax']) && $_POST['ajax']==='gift-form')
    {
    echo CActiveForm::validate($model);
    Yii::app()->end();
    }
    }
}

protected/views/draw/_view.php
<div class="view">

		<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('lottery_no')); ?>:</b>
	<?php echo CHtml::encode($data->lottery_no); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('client_id')); ?>:</b>
	<?php echo CHtml::encode($data->client_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('gift_id')); ?>:</b>
	<?php echo CHtml::encode($data->gift_id); ?>
	<br />


</div>

protected/views/draw/random.1.php
<?php
$cs = Yii::app()->getClientScript();
$cs->registerCss('mycss', '
    .output {
        margin: 15px;
        padding: 15px;
        background: black;
        border-radius: 10px;
        font-size: 70px;
        width: 80px;
        color: white;
        float: left;
    }
');
$url = Yii::app()->createUrl('draw/getrandom');
$url1 = Yii::app()->createUrl('draw/validate');
$url2 = Yii::app()->createUrl('draw/randomize');
$gift = $_GET['gift'];
$count = 9;
$js = <<<EOP
    $('#valid').hide();
    $('#coba').hide();
    $('#random').hide();
    

    $('#coba').click(function () {
           
        // Ajax Request
         $.ajax({
            cache:false,
            type: "GET",
            dataType: "json",
            url: "$url",
            success: function (loader) {
                //alert(loader);
                // This replace the retrieved data to the div after the setTimeOut function
                setTimeout(function () {
                    $('#nama').html('<h1><strong>' + loader.nama + '</strong></h1>');
                    $('#rek').html(loader.account);
                    $('#undi').html(loader.undian);
                }, 1000);
                pecah(loader.undian);
                //clearTimeout(t);
                generateNumber(0);
                tampil();
            }
        }); 

    });

    

    $('#start').one('click',function () {
        ambilPoin();
        //countdown();
        //$('#coba').trigger('click');
    });
    $('#stop').one('click',function () {
        cdpause();
    });

    var e = 0;
    $(window).keypress(function(event) {
        switch (event.keyCode) {  
        case 13:
            /*enter*/
             $('#start').trigger('click');
            e = 1;   
            break;
        case 32:
            /*spasi*/
            if(e == 1){
                $('#stop').trigger('click');
            }else{
                alert('anda belum pencet tombol enter !!');
            }
            break;
        case 117:
            /*u*/
             $('#ulang').trigger('click');
            break;
        case 115:
            /*S*/
             $('#sah').trigger('click');
            break; 
        case 98:
            /*b*/
            $('#back').trigger('click');
            break;        
        }
    });

    function tampil(){
        setTimeout(function(){
           $('#valid').show();
           $('#acak').hide();  
        },1000);
    };
    function pecah(loader){
        var num = loader;
        numbers=num.toString().split("").map(value=>parseInt(value,10));
        //alert(numbers);
    };
    function generateNumber(index) {
        var desired = numbers[index];
        //var duration = 1000;
        var duration = 1;

        var output = $('#output' + index); // Start ID with letter
        var started = new Date().getTime();

        animationTimer = setInterval(function() {
            if (output.text().trim() === desired || new Date().getTime() - started > duration) {
            clearInterval(animationTimer); // Stop the loop
            output.text(desired); // Print desired number in case it stopped at a different one due to duration expiration
            generateNumber(index + 1);
            } else {
            output.text(
                '' +
                Math.floor(Math.random() * 10)
            );
            }
        }, 10);
        clearTimeout(t);
    }


    $('#sah').click(function () {
        var noundi = $('div#undi').html();
        var gift = $gift;
        //alert(gift);
        //alert(noundi);
        $.ajax({
            cache:false,
            type: "GET",
            dataType: "json",
            data: {'no': noundi, 'gift':gift},
            url: "$url1",
            success: function (loader) {
                alert(loader);
                refreshPage()
            }
        }); 
        /* refreshPage() */
    }); 

    function refreshPage() {
       window.location = location.href;
    }

    $('#ulang').click(function(){
        refreshPage()
    });
    var t, count, count1;
	
	function cddisplay() {
		document.getElementById('output0').innerHTML = count;
		document.getElementById('output1').innerHTML = count1;
		document.getElementById('output2').innerHTML = count2;
		document.getElementById('output3').innerHTML = count3;
		document.getElementById('output4').innerHTML = count4;
		document.getElementById('output5').innerHTML = count5;
		document.getElementById('output6').innerHTML = count6;
		document.getElementById('output7').innerHTML = count7;
	}
	
	function countdown() {
		// starts countdown
		cddisplay();
		if (acak === 0) {
			// time is up
		} else {
			var myArrs =["0","2","4","3","1","8","6","7","5","9"];
			var myArrs1 =["0","4","2","8","7","3","6","1","5","9"];
			var myArrs2 =["8","4","2","9","1","3","5","7","6","0"];
			var myArrs3 =["9","0","6","2","7","3","4","3","5","1"];
			var myArrs4 =["7","1","3","5","4","6","0","2","8","9"];
			var myArrs5 =["4","6","5","8","7","9","0","1","3","2"];
			var myArrs6 =["2","5","4","8","7","3","6","1","0","9"];
			var myArrs7 =["1","9","4","3","5","7","2","6","5","8"];

			acak--;
			count = myArrs[urut];
			count1 = myArrs1[urut];
			count2 = myArrs2[urut];
			count3 = myArrs3[urut];
			count4 = myArrs4[urut];
			count5 = myArrs5[urut];
			count6 = myArrs6[urut];
			count7 = myArrs7[urut];
			urut++;
			if (urut == jumlah) urut = 0;
			t = setTimeout(countdown,100);
		}
	}
	
	function cdpause() {
		// pauses countdown
		//clearTimeout(t);
        //clearInterval(t);
        $('#coba').trigger('click');
    }

    function ambilPoin(){
        $.ajax({
            cache:false,
            type: "GET",
            dataType: "json",
            url: "$url2",
            success: function (loader) {
                alert(loader);
            }
        });
    }
    
	
	acak = 99999;
	urut = 0;
    count =  $count;
    count1 =  $count;
    count2 =  $count;
    count3 =  $count;
    count4 =  $count;
    count5 =  $count;
    count6 =  $count;
    count7 =  $count;
	jumlah = $count; 
	cddisplay();

      
EOP;
$cs->registerScript('random', $js, CClientScript::POS_END);
?>



<div class="row">
    <div class="col-xs-3"></div>
    <div class="col-xs-6" style="font-size:35px;" align="center"><b>Undian Tabungan Sakura</b></div>
    <div class="col-xs-3"></div>
</div>
<div class="row-fluid">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">	
        <div class="output" id="output0">0</div>
        <div class="output" id="output1">0</div>
        <div class="output" id="output2">0</div>
        <div class="output" id="output3">0</div>
        <div class="output" id="output4">0</div>
        <div class="output" id="output5">0</div>
        <div class="output" id="output6">0</div>
        <div class="output" id="output7">0</div>
    </div>
    <div class="col-xs-1"></div>    
</div>
<div class="row">&nbsp;</div>
<div class="row">&nbsp;</div>
<!-- <div class="row">&nbsp;</div> -->
<div class="row-fluid">
    <div id="acak">
        <?php if($model->result != '0'){?>

            <div class="col-xs-6" align="right">
                <?php $this->widget(
                    'booster.widgets.TbButton',
                    array(
                        'id'=>'coba',
                        'label' => 'ACAK',
                        'size' => 'large',
                        'context' => 'danger',
                    )
                ); ?>

                <?php $this->widget(
                    'booster.widgets.TbButton',
                    array(
                        'id'=>'start',
                        'label' => 'start',
                        //'size' => 'large',
                        'context' => 'danger',
                        //'htmlOptions'=> array('this.onclick' => 'null'),
                    )
                ); ?>
                <?php $this->widget(
                    'booster.widgets.TbButton',
                    array(
                        'id'=>'random',
                        'label' => 'random',
                        //'size' => 'large',
                        'context' => 'danger',
                        //'htmlOptions'=> array('this.onclick' => 'null'),
                    )
                ); ?>
            </div>
            <div class="col-xs-6" align="left">
                <?php $this->widget(
                    'booster.widgets.TbButton',
                    array(
                        'id'=>'stop',
                        'label' => 'stop',
                        //'size' => 'large',
                        'context' => 'danger',
                    )
                ); ?>
            </div>
        <?php }else{ ?>
        <div class="col-xs-12" align="center">
            <?php $this->widget(
                'booster.widgets.TbButton',
                array(
                    'id'=>'back',
                    'label' => 'kembali',
                    'context' => 'success',
                    'url'=>array('/gift/choose'),
                    'buttonType'=>'link',
                )
            ); ?>
        </div>
    <?php } ?>
    </div>
</div>    
<!-- <div class="row">&nbsp;</div> -->
<div class="row">&nbsp;</div>
<div class="row">&nbsp;</div>
<div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-3" style="font-size:25px">Nama Lengkap</div>
    <div class="col-xs-1">:</div>
    <div class="col-xs-5" id="nama" style="font-size:25px"></div>
    <div class="col-xs-3"></div>
</div>
<div class="row">&nbsp;</div>
<div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-3" style="font-size:25px">Nomor Rekening</div>
    <div class="col-xs-1">:</div>
    <div class="col-xs-3" id="rek"></div>
    <div class="col-xs-4">
        <div id="valid">
        <div class="col-xs-6" align="right">
            <?php $this->widget(
                'booster.widgets.TbButton',
                array(
                    'id'=>'sah',
                    'label' => 'SAH',
                    //'size' => 'large',
                    'context' => 'info',
                )
            ); ?>
        </div>
    <div class="col-xs-6" align="left">
        <?php $this->widget(
            'booster.widgets.TbButton',
                array(
                    'id'=>'ulang',
                    'label' => 'ulang',
                    //'size' => 'large',
                    'context'=>'primary'
                )
            ); ?>
    </div>
    </div>
    </div>
</div>
<div class="row">&nbsp;</div>
<div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-3" style="font-size:25px">Nomor Undian</div>
    <div class="col-xs-1">:</div>
    <div class="col-xs-4" id="undi"></div>
    <div class="col-xs-2"></div>
</div>
<div class="row"><img src="<?php echo Yii::app()->baseUrl;?>/images/<?php echo $model->image?>" width="250px"></img></div>
<div class="row">&nbsp;</div>
<!-- <div class="row">&nbsp;</div> -->
<?php /*
<div class="row-fluid">
    <div id="valid">
        <div class="col-xs-6" align="right">
            <?php $this->widget(
                'booster.widgets.TbButton',
                array(
                    'id'=>'sah',
                    'label' => 'SAH',
                    //'size' => 'large',
                    'context' => 'info',
                )
            ); ?>
        </div>
    <div class="col-xs-6" align="left">
        <?php $this->widget(
            'booster.widgets.TbButton',
                array(
                    'id'=>'ulang',
                    'label' => 'ulang',
                    //'size' => 'large',
                    'context'=>'primary'
                )
            ); ?>
    </div>
    </div>
</div>  
*/?>

protected/views/draw/result.php
<?php
$cs = Yii::app()->getClientScript();
$js = <<<EOP
 window.onload = setupRefresh;

    function setupRefresh() {
      setTimeout("refreshPage();", 20000); // milliseconds
    }
    function refreshPage() {
       window.location = location.href;
    }
	
EOP;
$cs->registerScript('result', $js, CClientScript::POS_END);

$this->breadcrumbs=array(
	'Draws'=>array('index'),
	'Manage',
);

$this->menu=array(
array('label'=>'List Draw','url'=>array('index')),
array('label'=>'Create Draw','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
$('.search-form').toggle();
return false;
});
$('.search-form form').submit(function(){
$.fn.yiiGridView.update('draw-grid', {
data: $(this).serialize()
});
return false;
});
");
?>


<?php //echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
	<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<div class="row">
    <div class="col-xs-3"></div>
<!--    <div class="col-xs-6" style="font-size:35px;" align="center"><b>Undian Tabungan Sakura</b></div>-->
    <div class="col-xs-3"></div>
</div>
<br><br><br><br><br><br><br><br><br>


<div class="row">
<!-- <div class="col-xs-1"></div> -->
<div class="col-xs-12" style="background: white">
	<?php $this->widget('booster.widgets.TbGroupGridView',array(
		'id'=>'draw-grid',
		'dataProvider'=>$model->search(),
		//'filter'=>$model,
		'summaryText'=>'',
		'type' => 'condensed bordered striped',
		//	'template' => "{items}",
		//'htmlOptions'=>array('class'=>'well'),
		'columns'=>array(
				array(
					'header'=>'Hadiah',
					'name'=>'gift',
					'value'=>'$data->gift_id != 0 ? $data->gift->name : ""',
				),
				array(
					'header'=>'No Undian',
					'name'=>'lottery',
					'value'=>'$data->lottery_no != 0 ? $data->lottery_no : "-"',
				),
				array(
					'header'=>'Nama Lengkap',
					'name'=>'nama',
					'value'=>'$data->client_id != 0 ? $data->client->fullname : "-"',
				),
				 array(
					'header'=>'No Rekening',
					'name'=>'member',
					'value'=>'$data->client_id != 0 ? $data->client->account_no : "-"',
				),
				//array('class'=>'booster.widgets.TbImageColumn')
				 
		),
		 'mergeColumns' => array('gift_id')
	)); ?>
    <br>

</div>
    <br><br>
    <div class="col-xs-12 pull-right" align="center">
        <?php $this->widget(
            'booster.widgets.TbButton',
            array(
                'id' => 'back',
                'label' => 'UNDIAN',
                'context' => 'success',
                'url' => array('/gift/choose'),
                'buttonType' => 'link',
            )
        ); ?>
    </div>
<!-- <div class="col-xs-1"></div> -->
</div>