protected/models/Gift.php
<?php

/**
 * This is the model class for table "gift".
 *
 * The followings are the available columns in table 'gift':
 * @property integer $id
 * @property string $name
 * @property string $type
 * @property integer $total
 * @property integer $result
 */
class Gift extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'gift';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, type, total, result', 'required'),
			array('total, result', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('type', 'length', 'max'=>15),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, type, total, result', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Name',
			'type' => 'Type',
			'total' => 'Total',
			'result' => 'Result',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('type',$this->type,true);
		$criteria->compare('total',$this->total);
		$criteria->compare('result',$this->result);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Gift the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ClientController.php
<?php

class ClientController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/column2';

/**
* @return array action filters
*/
public function filters()
{
return array(
'accessControl', // perform access control for CRUD operations
);
}

/**
* Specifies the access control rules.
* This method is used by the 'accessControl' filter.
* @return array access control rules
*/
public function accessRules()
{
return array(
array('allow',  // allow all users to perform 'index' and 'view' actions
'actions'=>array('index','view','reset'),
'users'=>array('*'),
),
array('allow', // allow authenticated user to perform 'create' and 'update' actions
'actions'=>array('create','update'),
'users'=>array('@'),
),
array('allow', // allow admin user to perform 'admin' and 'delete' actions
'actions'=>array('admin','delete'),
'users'=>array('admin'),
),
array('deny',  // deny all users
'users'=>array('*'),
),
);
}

/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
public function actionView($id)
{
$this->render('view',array(
'model'=>$this->loadModel($id),
));
}

/**
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
public function actionCreate()
{
$model=new Client;

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Client']))
{
$model->attributes=$_POST['Client'];
if($model->save())
$this->redirect(array('view','id'=>$model->id));
}

$this->render('create',array(
'model'=>$model,
));
}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
public function actionUpdate($id)
{
$model=$this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

if(isset($_POST['Client']))
{
$model->attributes=$_POST['Client'];
if($model->save())
$this->redirect(array('view','id'=>$model->id));
}

$this->render('update',array(
'model'=>$model,
));
}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
// we only allow deletion via POST request
$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))
$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
}
else
throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}

/**
* Lists all models.
*/
public function actionIndex()
{
$dataProvider=new CActiveDataProvider('Client');
$this->render('index',array(
'dataProvider'=>$dataProvider,
));
}

/**
* Manages all models.
*/
public function actionAdmin()
{
$model=new Client('search');
$model->unsetAttributes();  // clear any default values
if(isset($_GET['Client']))
$model->attributes=$_GET['Client'];

$this->render('admin',array(
'model'=>$model,
));
}

    public function actionReset(){
        $criteria = new CDbCriteria;
        $criteria->condition = 'status = 99';
        $model = Client::model()->updateAll(array('status'=>50),$criteria); 

       /*  $criteria2 = new CDbCriteria;
        $criteria2->condition = 'status = 2';
        $modelPoint = Point::model()->updateAll(array('status'=>1),$criteria2); */

        $poin=Yii::app()->db->createCommand()
        ->update(
            'point', 
            array(
                'status'=>'1',
            ), 
            'status=2'
        );
    }

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Client::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='client-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/controllers/DrawController.php
<?php

class DrawController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view', 'create', 'update', 'admin', 'result', 'random', 'getrandom', 'validate', 'randomize', 'result1'),
                'users' => array('*'),
            ),
            /* array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array(),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('delete'),
                'users'=>array('admin'),
            ), */
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('reset', 'cleardata', 'generate', 'generate2', 'generate3'),
                'users' => array('bpr'),
            ),
            array('deny',  // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new Draw;

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

        if (isset($_POST['Draw'])) {
            $model->attributes = $_POST['Draw'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);

// Uncomment the following line if AJAX validation is needed
// $this->performAjaxValidation($model);

        if (isset($_POST['Draw'])) {
            $model->attributes = $_POST['Draw'];
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        if (Yii::app()->request->isPostRequest) {
// we only allow deletion via POST request
            $this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        } else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider = new CActiveDataProvider('Draw');
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model = new Draw('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Draw']))
            $model->attributes = $_GET['Draw'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    public function actionResult()
    {

        $this->layout = 'column1';

        /* $criteria = new CDbCriteria;
        $criteria->compare('gift_id','1');
        //$model = Draw::model()->findAll($criteria);
        $model = new CActiveDataProvider('Draw', array(
				'criteria'=>$criteria,
			));
        
        $criteria2 = new CDbCriteria;
        $criteria2->compare('gift_id','2');
        //$model2 = Draw::model()->findAll($criteria2);
        $model2 = new CActiveDataProvider('Draw', array(
				'criteria'=>$criteria2,
			));
        
        $criteria3 = new CDbCriteria;
        $criteria3->compare('gift_id','3');
        //$model3 = Draw::model()->findAll($criteria3);
        $model3 = new CActiveDataProvider('Draw', array(
				'criteria'=>$criteria3,
			));
        
        $criteria4 = new CDbCriteria;
        $criteria4->compare('gift_id','4');
        //$model4 = Draw::model()->findAll($criteria4);
        $model4 = new CActiveDataProvider('Draw', array(
				'criteria'=>$criteria4,
			));
        
        $criteria5 = new CDbCriteria;
        $criteria5->compare('gift_id','5');
        //$model5 = Draw::model()->findAll($criteria5);
        $model5 = new CActiveDataProvider('Draw', array(
				'criteria'=>$criteria5,
			));
        
        $criteria6 = new CDbCriteria;
        $criteria6->compare('gift_id','6');
        //$model6 = Draw::model()->findAll($criteria6);
        $model6 = new CActiveDataProvider('Draw', array(
				'criteria'=>$criteria6,
			)); */


        $model = new Draw('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Draw'])) {
            $model->attributes = $_GET['Draw'];
        }

        $this->render('result', array(
            'model' => $model,
            /* 'model2'=>$model2,
            'model3'=>$model3,
            'model4'=>$model4,
            'model5'=>$model5,
            'model6'=>$model6, */
        ));
    }

    public function actionRandom($gift)
    {
        /*get Hadiah*/
        $model = Gift::model()->findByPk($gift);

        /*begin random*/
        $dataNo = Client::model()->findAll(array(
            'condition' => 'status = 50',
        ));
        $arrData = array();
        foreach ($dataNo as $val) {
            $arrData[$val->id] = $val->id;
        }
        //print_r($arrData);
        //$random = array_rand($arrData,1);
        for ($i = 1; $i <= 20; $i++) {
            $random = array_rand($arrData, 1);
        }
        /* echo $random;
        echo '**'; */
        $range = Client::model()->find(array(
            'select' => 'id, start_no, finish_no',
            'condition' => 'id = :r',
            'params' => array(':r' => $random),
        ));

        $min = $range->start_no;
        $max = $range->finish_no;

        for ($i = 1; $i <= 20; $i++) {
            $undian = rand($min, $max);
        }
        /* echo $undian; */
        /*emd random*/

        //$count = '9';

        //$arrs = '["' . implode('", "', $arrUndian) . '"]';
        $this->render('random', array(
            'model' => $model,
            //'arrs'=>$arrs,
            //'count'=>$count,
        ));
    }

    public function actionRandomize()
    {
        do {
            $comm = Yii::app()->db->createCommand("
				(SELECT CEIL(RAND() * MAX(id)) as a FROM point where status=1)
				");
            $x = $comm->queryAll();
            $idPoint = $x[0]['a'];

            $user = Yii::app()->db->createCommand()
                ->select('id, point, client_id')
                ->from('point')
                ->where('id=:id', array(':id' => $idPoint))
                ->queryRow();
        } while ($user === false);

        $point2020 = $user;
        $poin = $user['point'];
        $cid = $user['client_id'];

        $command = Yii::app()->db->createCommand("select id,cif,account_no,fullname,status from client WHERE id='$cid'");
        $model = $command->queryRow();
        if ($model != null && $model['status'] == '50') {
            $temp = array("id" => $model['id'], "undian" => $poin, "nama" => $model['fullname'], "account" => $model['account_no'], "cif" => $model['cif']);
        } else {
            $dataNo = Client::model()->findAll(array(
                'condition' => 'status = 50',
            ));
            $arrData = array();
            foreach ($dataNo as $val) {
                $arrData[$val->id] = $val->id;
            }

            $random = array_rand($arrData, 1);

            $range = Client::model()->find(array(
                'select' => 'id, start_no, finish_no',
                'condition' => 'id = :r',
                'params' => array(':r' => $random),
            ));

            $min = $range->start_no;
            $max = $range->finish_no;

            for ($i = 1; $i <= 20; $i++) {
                $undian = rand($min, $max);
            }

            $command1 = Yii::app()->db->createCommand("select id,cif,account_no,fullname from client WHERE ('$undian' BETWEEN start_no and finish_no) AND status=50");
            $model1 = $command1->queryRow();
            file_put_contents('' . $undian . '.txt', $poin . 'diganti' . $undian);
            $temp = array("id" => $model1['id'], "undian" => $undian, "nama" => $model1['fullname'], "account" => $model1['account_no'], "cif" => $model1['cif']);

        }
        $point2020['data'] = $temp;
        echo json_encode($point2020);
    }

protected/views/gift/_form.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'id'=>'gift-form',
	'enableAjaxValidation'=>false,
)); ?>

<p class="help-block">Fields with <span class="required">*</span> are required.</p>

<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldGroup($model,'name',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>50)))); ?>

	<?php echo $form->textFieldGroup($model,'type',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>15)))); ?>

	<?php echo $form->textFieldGroup($model,'total',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<?php echo $form->textFieldGroup($model,'result',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

<div class="form-actions">
	<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType'=>'submit',
			'context'=>'primary',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
		)); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/gift/_search.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldGroup($model,'id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'name',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>50)))); ?>

		<?php echo $form->textFieldGroup($model,'type',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>15)))); ?>

		<?php echo $form->textFieldGroup($model,'total',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'result',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

	<div class="form-actions">
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType' => 'submit',
			'context'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/gift/_thumb.php
<div class="col-sm-6 col-sm-3" style="padding-top: 80px;padding-left: 40px">
<?php //echo $data->result;?>
    <div class="thumbnail">
        <?php if($data->type != 'grandprize'){?>
        <a href="<?php echo $data->result != 0 ? Yii::app()->createUrl('draw/random',array('gift'=>$data->id)) : '#'?>"><img src="<?php echo Yii::app()->baseUrl;?>/images/<?php echo $data->image?>" alt=""></a>
        <?php }else{ ?>
        <a href="<?php echo Yii::app()->createUrl('draw/random',array('gift'=>$data->id)) ?>"><img  src="<?php echo Yii::app()->baseUrl;?>/images/<?php echo $data->image?>" alt=""></a>
        <?php } ?>
        <div class="caption">
            <h2 align="center"><?php echo $data->name?></h2>
            <p align="center">
                <?php if($data->result != 0){
                    if($data->type != 'grandprize'){
                        $this->widget('booster.widgets.TbButton',array(
                            'id'=>'pil',
						    'label' => '',
						    'url'=>array('draw/random','gift'=>$data->id),
							'icon'=>'play-circle',
							'buttonType'=>'link',
							//'size'=>'large',
							'context'=>'info',
						));
                    }else{
                        $this->widget('booster.widgets.TbButton',array(
                            'id'=>'pilih',
						    'label' => '',
						    'url'=>array('draw/random','gift'=>$data->id),
							'icon'=>'play-circle',
							'buttonType'=>'link',
							//'size'=>'large',
							'context'=>'info',
						));     
                    }    
                   
                }else{
                     $this->widget('booster.widgets.TbButton',array(
						    'label' => '',
						    'url'=>array('draw/random'),
							'icon'=>'play-circle',
							'buttonType'=>'link',
							//'size'=>'large',
							'context'=>'info',
                            'disabled'=>true,
						));

                }?>
            </p>
        </div>
    </div>
</div>

protected/views/gift/_view.php
<div class="view">

		<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('type')); ?>:</b>
	<?php echo CHtml::encode($data->type); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('total')); ?>:</b>
	<?php echo CHtml::encode($data->total); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('result')); ?>:</b>
	<?php echo CHtml::encode($data->result); ?>
	<br />


</div>

protected/views/gift/admin.php
<?php
$this->breadcrumbs=array(
	'Gifts'=>array('index'),
	'Manage',
);

$this->menu=array(
array('label'=>'List Gift','url'=>array('index')),
array('label'=>'Create Gift','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
$('.search-form').toggle();
return false;
});
$('.search-form form').submit(function(){
$.fn.yiiGridView.update('gift-grid', {
data: $(this).serialize()
});
return false;
});
");
?>

<h1>Manage Gifts</h1>

<p>
	You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>
		&lt;&gt;</b>
	or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
	<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('booster.widgets.TbGridView',array(
'id'=>'gift-grid',
'dataProvider'=>$model->search(),
'filter'=>$model,
'columns'=>array(
		'id',
		'name',
		'type',
		'total',
		'result',
array(
'class'=>'booster.widgets.TbButtonColumn',
),
),
)); ?>

protected/views/gift/choose.php
<?php 
$cs = Yii::app()->getClientScript();
$url = Yii::app()->createUrl('client/reset');
$js = <<<EOP
    $('#pilih').click(function () {
        $.ajax({
            cache:false,
            type: "GET",
            dataType: "json",
            url: "$url",
            success: function (loader) {
                alert(loader);
            }
        }); 
    });

EOP;
$cs->registerScript('gift', $js, CClientScript::POS_END);
?>
<!--<div class="row">-->
<!--    <div class="col-xs-3"></div>-->
<!--    <div class="col-xs-6" style="font-size:35px;" align="center"><b>Undian BPR Natasha</b></div>-->
<!--    <div class="col-xs-3"></div>-->
<!--</div>-->
<!--<div class="row">&nbsp;</div>-->
<!--<div class="row">&nbsp;</div>-->
    <div class="row-fluid" style="margin-top: 100px;margin-left: 180px;">
<?php 
    echo CHtml::openTag('div', array('class' => 'row-fluid'));
    $this->widget(
        'booster.widgets.TbThumbnails',
        array(
            'dataProvider' => $dataProvider,
            'template' => "{items}\n{pager}",
            'itemView' => '_thumb',
        )
    );
    echo CHtml::closeTag('div');
?>
</div>     

protected/views/gift/create.php
<?php
$this->breadcrumbs=array(
	'Gifts'=>array('index'),
	'Create',
);

$this->menu=array(
array('label'=>'List Gift','url'=>array('index')),
array('label'=>'Manage Gift','url'=>array('admin')),
);
?>

<h1>Create Gift</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/gift/index.php
<?php
$this->breadcrumbs=array(
	'Gifts',
);

$this->menu=array(
array('label'=>'Create Gift','url'=>array('create')),
array('label'=>'Manage Gift','url'=>array('admin')),
);
?>

<h1>Gifts</h1>

<?php $this->widget('booster.widgets.TbListView',array(
'dataProvider'=>$dataProvider,
'itemView'=>'_view',
)); ?>

protected/views/gift/update.php
<?php
$this->breadcrumbs=array(
	'Gifts'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

	$this->menu=array(
	array('label'=>'List Gift','url'=>array('index')),
	array('label'=>'Create Gift','url'=>array('create')),
	array('label'=>'View Gift','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Gift','url'=>array('admin')),
	);
	?>

	<h1>Update Gift <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/gift/view.php
<?php
$this->breadcrumbs=array(
	'Gifts'=>array('index'),
	$model->name,
);

$this->menu=array(
array('label'=>'List Gift','url'=>array('index')),
array('label'=>'Create Gift','url'=>array('create')),
array('label'=>'Update Gift','url'=>array('update','id'=>$model->id)),
array('label'=>'Delete Gift','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
array('label'=>'Manage Gift','url'=>array('admin')),
);
?>

<h1>View Gift #<?php echo $model->id; ?></h1>

<?php $this->widget('booster.widgets.TbDetailView',array(
'data'=>$model,
'attributes'=>array(
		'id',
		'name',
		'type',
		'total',
		'result',
),
)); ?>